### ISSUE TITLE
[FEATURE] Optimize front-end performance

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1138]
### Describe the feature you want 描述你的功能需求

The home page performance result is https://gtmetrix.com/reports/midbai.com/XwfZtO8j/.
Why was issue #843 closed? Do you have any idea how to fix that, Maybe I can do some of the tasks.

![image](https://github.com/HEIGE-PCloud/DoIt/assets/7602218/4787d8fa-ecb8-4de6-a510-ab8b595dc9cd)

![image](https://github.com/HEIGE-PCloud/DoIt/assets/7602218/1472b427-5da2-4180-a069-ed98666db1a0)

### Useful reference 有价值的参考

https://github.com/HEIGE-PCloud/DoIt/pull/619
https://github.com/HEIGE-PCloud/DoIt/issues/843
https://github.com/HEIGE-PCloud/DoIt/issues/616

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
# suggestions

*    Use Rollup for tree-shaking and bundling in JavaScript, then use ESM’s `await import` syntax in `theme.js` to dynamically import the required libraries.

*    For CSS, I think there are two approaches. One is to replace it entirely with Tailwind to reduce coupling. The other is to divide it into some small files like the critical CSS way. I might prefer the former one because the latter can be time-consuming and labor-intensive for a large static generated site. Additionally, I think [[what Stylex has adopted](https://stylexjs.com/docs/learn/thinking-in-stylex/#one-small-file-over-many-smaller-files)](https://stylexjs.com/docs/learn/thinking-in-stylex/#one-small-file-over-many-smaller-files) is inspiring. 

# but

Benchmarking is benchmarking, and the improvements from these optimizations are limited in most user scenarios nowadays. Personally, I don’t find Doit’s loading speed unacceptable. The purpose of using Hugo as a framework is simplicity and developers have to consider most things themselves. It would be difficult to achieve best practices in so many aspects, or it will come with great complexity, which hugo is not born for.

**Comment by HEIGE-PCloud** [comment]
I would say the performance of DoIt is _fine_ currently based on real world statistics from [Google PageSpeed Insights](https://pagespeed.web.dev/analysis/https-hugodoit-pages-dev/9b092nqvoa?form_factor=desktop) (Collected from all Chrome users) and [Cloudflare Pages Analytics](https://github.com/HEIGE-PCloud/DoIt/assets/52968553/949c2d4a-e084-4bb7-a699-877b02c97ebe) (The hosting service provider).

The main reason why multiple attempts have been closed as you pointed out is because I have limited personal bandwith on maintaining this project, and all these changes are rather complicated. Also, a lot of low hanging fruits you might think of have already been implemented. To make things worse, we have zero testing for DoIt so it takes a lot of care to make sure nothing is broken and backwards compatibility is properly kept.

You will find most external JavaScript and CSS libraries are only loaded if required based on individual page configurations (See KaTeX as an example). And of course all JavaScript and CSS bundles are minified as you suggested [here](https://github.com/HEIGE-PCloud/DoIt/issues/843#issuecomment-1864206645).

Here are some further optimisation ideas if you want to look into it:

- Load LightGallery only when the user clicks the image (Already implemented for search)
- Get rid of clipboard.js (I think now all browsers have a consistent API for this)
- Inline FontAwesome icons (Quite tricky because of this https://hugodoit.pages.dev/theme-documentation-content/#fontawesome)
- Get rid of animate.css and cherry pick the necessary animations
- Refactor all SCSS styles into tailwindCSS. (Quite tricky because of the sheer volume of the styles and dependencies in some JavaScript code)
- Upgrade deprecated dependencies (e.g. `autocomplete` for search, LightGallery for photos etc)
- Refactor code blocks to use the markdown render hook and reduce JavaScript dependency.

**Comment by HEIGE-PCloud** [comment]
<img width="1069" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/40de13b2-fefc-467f-9d24-21d2b07f16a1">

https://pagespeed.web.dev/analysis/https-hugodoit-pages-dev/64bexwzvnp?form_factor=mobile

This turns out to be better than what I expected. I am closing this for now. We can open up individual issues for each optimisation idea later on.
