### ISSUE TITLE
[BUG] Disable Black Mode

### ISSUE THREAD

**Issue by hugosxm** [HEIGE-PCloud/DoIt#1176]
### Describe the bug 描述你遇到的错误

HI, i just switched from loveit, I wonder if there is a way to select "enabled" theme ? For exemple I want dark and light but not black as I need to manager 3 different type of image versus only two If i can disable it...

Thanks

**Comment by s2gh** [comment]
@HEIGE-PCloud please add an option to do that in config.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Actually we had a [pr](https://github.com/HEIGE-PCloud/DoIt/pull/795) liked this before, just grab the the [code](https://github.com/HEIGE-PCloud/DoIt/pull/795/files) and it should works fine. 

Below is the tldr why this pull request has been closed.

@HEIGE-PCloud  is actually unsure whether to continue maintaining the light, dark, and black themes. The reason for adding the black theme on top of DoIt initially was because they were not satisfied with the design of DoIt’s dark theme - its main color tone was more gray than black, which resulted in a poor reading experience in low-light environments. The highlight color blue was also not harmonious with the main gray color as it had not been adjusted properly. 

In fact, the author hopes that maybe we can find a way, try to design a new dark theme that unifies the existing dark and black themes, thus avoiding many similar maintenance burdens.

**Comment by HEIGE-PCloud** [comment]
Closing this for now, we will continue to track this in https://github.com/HEIGE-PCloud/DoIt/issues/654
