### ISSUE TITLE
Redesign the color palette

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#1245]
## Background

Currently, we have three color themes: `light`, `dark` and `black`. The `black` theme was added when DoIt was derived from LoveIt due to my dissatisfaction of the `dark` theme - it's just not dark enough.

This turns out to be not a good idea #654 #1176 and creates a lot of duplication.

## Now

The thing we really need is a _properly designed_ color palette that looks nice, has good accessbility, conveys the correct semantics etc. Then it would be relatively easy to integrate that with [Tailwind CSS](https://tailwindcss.com/docs/customizing-colors). Hopefully we can make the dark theme better and get rid of the black theme completely.

The problem is that I have no idea how to design a good color palette so I am inclined to just borrow https://primer.style/foundations/primitives/color and make some adjustments on top of it.

Any help or suggestions will be appreciated.

**Comment by CXwudi** [comment]
I think borrowing the design from GitHub is good. I love GitHub dark theme and personally use Dark dimmed for Night time

**Comment by kkbt0** [comment]
Color CSS variables maybe a good idea. 
Like this https://github.com/alex-shpak/hugo-book/blob/master/assets/themes/_auto.scss
This seems to make it easier to expand or delete unnecessary themes. 
Example:
- https://github.com/rebron1900/11ty-book/blob/master/src/assets/sass/_defaults.scss
- https://github.com/rebron1900/11ty-book/tree/master/src/assets/sass/themes

**Comment by kkbt0** [comment]
I have made some attempts, but it has to be said that it is more complicated than expected. I change a color `$global-background-color`  in this commit .

- https://github.com/kkbt0/DoIt/commit/8db166613b3adebd8242dbf15e110c645087ecb4
- https://github.com/kkbt0/DoIt/commit/69b6e0a85dd65f46e73d56cdee0ef084267c35c2

---

Sass is `.single .content kbd { style }` . But html template don't have any `kbd` . This may be for some input box styles in JavaScript.

So we need https://github.com/tailwindlabs/tailwindcss-typography to add style to any vanilla HTML we don’t control.

And this should be able to use SCSS for style overlay.

(But this requires careful verification of the specific effect, ensuring that word spacing, color, and so on are not incorrectly covered by tailwindcss typography. Because I haven't configured the typography font color background yet, some colors have been overwritten by the typography default style now.)

```css
.prose-kbd\:tw-bg-global-background-color :is(:where(kbd):not(:where([class~=tw-not-prose],[class~=tw-not-prose] *))) {
    background-color: var(--global-background-color)
}
```

This may bring compatibility issues, but most browsers now support . 


---

And `.search-dropdown .dropdown-menu` class  depend on CSS Descendant combinator. Class `.dropdown-menu`  is the style required by autocomplete.min.js .

So we need a custom plugins like this. Ensure that the Tailwindcss style can cover the HTML generated by JavaScript.

https://github.com/tailwindlabs/tailwindcss/discussions/7541
https://play.tailwindcss.com/tWrJX5Rapi

Similarly,  DoIt/assets/lib/valine/Valine.scss `.v[data-class=v]  .vcards .vcard .vcontent.expand:after`  is also hard to use Tailwindcss  color class.

**Comment by HEIGE-PCloud** [comment]
Thanks for looking into this and raising the challenge. I agree that Tailwind does not work very well with foreign contents, and I don't think we have to move 100% to Tailwind - a mix between Tailwind and SCSS setup may be the best solution here. 

I think we can still centralise the color palette using CSS variables, what you've done in https://github.com/kkbt0/DoIt/commit/8db166613b3adebd8242dbf15e110c645087ecb4 is awesome. Then, for elements that directly present in the HTML that we control, we use Tailwind to style their color, and for foreign content, we can keep our SCSS setup like what you have done here https://github.com/HEIGE-PCloud/DoIt/pull/1253/commits/058c62e5c6bcf7de8bb6ccf331a07d5e68d9df80

I think in this way, we have the best of both worlds.

**Comment by HEIGE-PCloud** [comment]
I think the value of Tailwind mainly reflects in many of the "mostly isolated" components in DoIt. Features like 

https://github.com/HEIGE-PCloud/DoIt/blob/a3970ec1af30d027102cd8889701877390d5d8ba/assets/css/_partial/_single/_showcase.scss

https://github.com/HEIGE-PCloud/DoIt/blob/a3970ec1af30d027102cd8889701877390d5d8ba/assets/css/_partial/_single/_sponsor.scss

https://github.com/HEIGE-PCloud/DoIt/blob/a3970ec1af30d027102cd8889701877390d5d8ba/assets/css/_partial/_single/_admonition.scss

can hopefully be decoupled from the central style sheet and made future maintenance easier.

Also, about 90% of our current SCSS bundle is unused on the homepage

<img width="1433" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/34223a1a-e190-4fd8-bdee-1584ac3a0d66">

I hope by moving to an atomic CSS solution, we can reduce duplications in styles and improve the performance. #1138

**Comment by HEIGE-PCloud** [comment]
Do you like the new design?

<img width="1440" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/31c2306c-7293-44ad-a1d3-3b1327ca73a0">


<img width="1427" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/a99973c9-9313-48f2-bb2c-10c7426be33c">

**Comment by CXwudi** [comment]
That's great job for both of you, It would be great if there is a link where I can check how it looks in the post.

**Comment by kkbt0** [comment]
https://github.com/HEIGE-PCloud/DoIt/pull/1253
https://do-dun87dsqt-pclouds-projects.vercel.app/

And now it has a smaller css size.
