### ISSUE TITLE
[FEATURE] Shortcode for github code

### ISSUE THREAD

**Issue by himazawa** [HEIGE-PCloud/DoIt#1305]
### Describe the feature you want 描述你的功能需求

I would like to see a shortcode to embed code from github specifying the file, line start and line end

### Useful reference 有价值的参考

Something like that should do the trick, the issue is that this is currently not working. https://github.com/nkmk/hexo-tag-github-code

**Comment by HEIGE-PCloud** [comment]
May I ask what's a good use case for this?

**Comment by himazawa** [comment]
Sure, I write technical blogs detailing vulnerability I found in the source of applications and embedding it directly from github will avoid massive copy-pasting. Same for everyone that write programming blogposts analyzing sources.
[Here ](https://appsec.space/posts/mycroft-ai-rce/) you can find an example

**Comment by HEIGE-PCloud** [comment]
I would recommend copy-pasting in these cases. GitHub's links are by no mean permanent. The source repository might be made private or deleted at any time. If a tag or a branch name is used to reference a file instead of its git hash, then the content of the page might also change.

In fact, one almost never wants to do this. No one wants to wake up one day and finds that half of code blocks on one’s blog disappear because some GitHub repository was deleted.

**Comment by himazawa** [comment]
You are correct, closing the issue
