### ISSUE TITLE
[BUG] Cannot render the dollar sign

### ISSUE THREAD

**Issue by gnohz** [HEIGE-PCloud/DoIt#173]
### Describe the bug 描述你遇到的错误

dollar sign does not render correctly

### Expected behavior 期待的行为

In the markdown, if `\$100`, we should see $100, but I got

<img width="266" alt="Screen Shot 2021-08-08 at 11 52 49 AM" src="https://user-images.githubusercontent.com/21259404/128642679-df8fcfe0-06dd-4e35-94b8-732b56642881.png">

By the way, I didn't have the problem with other themes.

**Comment by HEIGE-PCloud** [comment]
The content between two dollar signs will be rendered as a math formula if you have enabled it.

Related Documentation: https://hugodoit.pages.dev/theme-documentation-content/#mathematical-formula

The easiest way to solve it is to turn off the math formula rendering by adding 

```
math:
  enable: false
```

to the front matter.

**Comment by gnohz** [comment]
So I cannot have math formula on and also to print a dollar sign together?
I mean `$100$` should be treated differently from `\$100`, right? The first means in the math environment, the latter means to read as a dollar sign using the escape character `\`.

**Comment by HEIGE-PCloud** [comment]
It is not Hugo who renders the math formula, and `\$` is not really escaping anything.

No matter you put `$...$` or `\$...$`, it will remain unchanged in the final HTML generated by Hugo. The math formula rendering happens when the page is loading. KaTeX will render everything between two delimiters, for this case, two dollar signs. What "escape character" you put to the dollar sign does not matter as you are not really escaping anything.

The solution is to change the delimiters by editing the `config.toml` to manually set it to something other than the dollar sign. For example:

```toml
[params.page.math]
  enable = true
  blockLeftDelimiter = "\\["
  blockRightDelimiter = "\\]"
  inlineLeftDelimiter = "\\("
  inlineRightDelimiter = "\\)"
```

Please upgrade the DoIt theme to the latest commit as the logic for setting delimiters configs has been updated.
