### ISSUE TITLE
[BUG] Waline can't send photo and seriesNavigation doesn't show up

### ISSUE THREAD

**Issue by York-Shawn** [HEIGE-PCloud/DoIt#389]
### Describe the bug 描述你遇到的错误

1. Waline can't send photo while `uploadImage` is set to true
2. I create my own series which contain 2 posts, activate `seriesNavigation` in **config.toml**, and nav is still missing. 

### Expected behavior 期待的行为

1. Can you change the Waline src, cause after I modified the comment.html in `layouts/partial`, the image-uploading just worked.
2. Is something in `exampleSite` is needed for the nav, cause I can't run your post in exampleSite.

### Screenshots 屏幕截图
![image](https://user-images.githubusercontent.com/55875478/145722035-512c9c46-7187-4175-b786-52dfcf6609ee.png)
![image](https://user-images.githubusercontent.com/55875478/145722088-3b43759b-8523-4294-8f86-fc6cf3866903.png)
![image](https://user-images.githubusercontent.com/55875478/145722239-1d0d11a2-8097-4d32-a4d2-c26933fc5fd6.png)

### Build Environment 构建环境

- OS: WSL2/Ubuntu
- Theme version/commit 0.2.13
- Hugo version 90.0+extended

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: Windows10
- Browser Chrome

**Comment by HEIGE-PCloud** [comment]
1. I have updated Waline to its latest version, it should work now.
2. Do not add space in the series id. For example, use `series = [ series-name ]` instead of `series = [ series name ]`. Then create a `series/<id>/_index.md` under the content folder to set the series name as demonstrated in the [exampleSite](https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/content/series/getting-start/_index.en.md). It causes Hugo some problems to manage an id with space inside...

**Comment by York-Shawn** [comment]
Thanks for your reply. After changing different values, I finally made it, it seems like upper case is not allowed if you wanna enable seriesNavigation. I don't know if it's the `series` value or the directory name under series directory that caused this. But anyway, it just works.

**Comment by eyllanesc** [comment]
> 2\. `series = [ series name ]`.

or maybe: `series = [ "series name" ].`?

**Comment by York-Shawn** [comment]
mine is `series: ["series-name"]`

**Comment by HEIGE-PCloud** [comment]
I guess the way it works is that if a series name contains uppercase characters or spaces `Series Name`, it will be converted into `series-name` as an internal id, and the `Series Name` will be set to its name as a separate variable. (Just guess how it works based on its behaviour, have not checked Hugo's source code.)

<img width="554" alt="image" src="https://user-images.githubusercontent.com/52968553/145855557-e58c740c-c338-4543-8d88-88950d7ac720.png">

Which is what happens to that test series in the exampleSite.

https://github.com/HEIGE-PCloud/DoIt/blob/d38eb199b7648542dad2f4c9ecdbfff56215cbf3/layouts/posts/single.html#L156-L158

When I `{{ range $key, $value := .Site.Taxonomies.series }} `, the `$key` I get is its internal id instead of its series name, so when I compare it with the `$params.series` which stores the series name in the front matter, it might not match. So it only works when the series id is input in the front matter.

I am not sure whether I can get the series name from its id or vice versa... But there seems to have room for improvements.

**Comment by HEIGE-PCloud** [comment]
It should work correctly now with any series name.

https://hugodoit.com/series-taxonomy-tests/
