### ISSUE TITLE
[FEATURE] Add Telegram social share button for pages

### ISSUE THREAD

**Issue by digitaltwinz** [HEIGE-PCloud/DoIt#397]
### Useful reference
https://telegram.org/faq#q-what-is-telegram-what-do-i-do-here

If available, provide useful links to fulfill the feature.
https://core.telegram.org/widgets/share
https://upload.wikimedia.org/wikipedia/commons/8/83/Telegram_2019_Logo.svg

### Button image
[![image](https://img.favpng.com/24/24/8/telegram-logo-computer-icons-png-favpng-mDD6hkTsGdjWGjTT3Ta4KXqBy_t.jpg)](url)

**Comment by digitaltwinz** [comment]
@eyllanesc @HEIGE-PCloud the share button is not showing up for some reason. Can you please verify its functionality? Thanks in advance!

**Comment by eyllanesc** [comment]
@digitaltwinz Have you added `Telegram = true ` in `[params.page.share]` section  to your config.toml? 

https://github.com/HEIGE-PCloud/DoIt/blob/8793250794f5331005079f082e205eb9f11503ce/exampleSite/config.toml#L794

If you check [the demo](https://hugodoit.pages.dev/) you will see that it has been added.

<sub>**Note:** If you want to see that any feature works then use the [exampleSite](https://github.com/HEIGE-PCloud/DoIt/tree/main/exampleSite) of the latest version available since many times users do not configure the [config.toml](https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/config.toml) correctly. </sub>

**Comment by digitaltwinz** [comment]
@eyllanesc It turned out that I forgot to update the second file (layouts/partials/plugin/share.html) in my repo. Now it is OK. Thanks!
