### ISSUE TITLE
[BUG] 文章md文件中添加PJAX函数后导致页面出现 “空引用” 问题，查看demo

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#433]
### 文章 `md` 文件中添加PJAX函数后导致页面出现 “空引用” 问题

我在文章中添加 PJAX 函数控制 Twikoo 评论的统一性。
在文章 `md` 源文件中添加了PJAX函数后，页面上会出现一个空的引用： `<blockquote></blockquote>`
并没有输入一个空的 `>`。

Hugo版本：0.88.1，DoIt版本：0.2.13

demo：[demo](https://real-nicholas.github.io)，请帮忙排查一下！

如图：
<img width="979" alt="Screenshot 2021-12-29 at 17 13 31" src="https://user-images.githubusercontent.com/29486126/147646194-0a2bcba9-d9ed-4cfc-bb76-95c4a11e3013.png">

**Comment by eyllanesc** [comment]
@real-nicholas Could you share the source code (with the pjax function) of the files that generate both articles of your blog?  You should also share the config.toml. Analyzing the cause of the problem with only the error is almost impossible, for this much more information is necessary(minimal and workable example), such as the inputs (the source code).

**Comment by ghost** [comment]
these are my raw files:
https://raw.githubusercontent.com/real-nicholas/real-nicholas.github.io/main/issues/testing-1.md
https://raw.githubusercontent.com/real-nicholas/real-nicholas.github.io/main/issues/testing-2.md
https://github.com/real-nicholas/real-nicholas.github.io/blob/main/issues/config.toml

**Comment by eyllanesc** [comment]
@real-nicholas Have you verified that this problem does not occur in other themes?

**Comment by ghost** [comment]
@eyllanesc 
No, I haven't. 

Actually, it worked normally last month, but it was like this after I updated the theme last week.

**Comment by eyllanesc** [comment]
@real-nicholas In general, when you have a project that has N technologies, it implies that each technology can introduce its own bugs, so the task of the developer is to determine which technology has (or does not have) the bug. Given this my question to rule out that this project is the cause of this bug, for example if the problem is repeated in another theme then the problem is not caused by the themes but by the technology that converts the markdown to html.

In this case, there is a better strategy if you want to execute a javascript code, and you must follow the following steps: 

- Put your code in a .js file under the assets folder

	```console
	├── assets
	│   └── js
	│       └── issue433.js
	├── config.toml
	├── content
    ...
	```
     issue433.js

	```javascript
	window.TWIKOO_MAGIC_PATH="/testing-1/"
	document.addEventListener('pjax:send', function () {
	    window.TWIKOO_MAGIC_PATH=""
	});
	```
- And then you edit your post to add the javascript: 

	```md
	---
	title: "Testing 1"
	date: 2021-12-29T15:58:27+08:00
	categories: ["x"]
	tags: ["x", "x"]
	toc: false
	draft: true
	license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
	library:
	  js:
	    somejs: "js/issue433.js"
	---
	Start here to write...

	这篇文章的 `md` 源文件中 **包含**  `Pjax` 函数，出现了空的 `<blockquote></blockquote>`：
	```

<sub>Note: The problem does not have to do either pjax but with any javascript (if you replace your code with `console.log("Hello world")` you will see that the problem persists).</sub>

**Comment by eyllanesc** [comment]
Another option is to use the [shortcode script](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#12-script).

```markdown
{{< script >}}
 window.TWIKOO_MAGIC_PATH="/testing-1/"
 document.addEventListener('pjax:send', function () {
     window.TWIKOO_MAGIC_PATH=""
 });
{{< /script >}}
```

**Comment by eyllanesc** [comment]
@real-nicholas If my comments helped solve your problem then don't forget to close the issue.

**Comment by ghost** [comment]
@eyllanesc thanks.
I have tried to use shortcode script, but I found another interesting problem: this script can sometimes be parsed into the source file of the webpage by Hugo, sometimes it won't, and the reason and rule can't be determined. Therefore, there is no guarantee that shortcode script can write PJAX script into the source file of the webpage.

I'm not going to consider dealing with pjax now.
