### ISSUE TITLE
[BUG] Error build failed: Could not resolve "lazysizes"

### ISSUE THREAD

**Issue by todosrc** [HEIGE-PCloud/DoIt#475]
S E:\staticsite> hugo server -D
Start building sites … 
hugo v0.92.1-85E2E862+extended windows/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
WARN 2022/02/20 14:35:22 

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.
ERROR 2022/02/20 14:35:22 js.Build failed: Could not resolve "lazysizes"
ERROR 2022/02/20 14:35:22 js.Build failed: Could not resolve "tablesort"
ERROR 2022/02/20 14:35:23 JSBUILD: failed to transform "js/lib/mermaid.js" (application/javascript): Could not resolve "mermaid"
Error: Error building site: JSBUILD: failed to transform "js/theme.js" (application/javascript): Could not resolve "topbar"
Built in 1899 ms

**Comment by eyllanesc** [comment]
add `bundle = false` in:

https://github.com/HEIGE-PCloud/DoIt/blob/e539c9ba5f97e5befbfc605118bdd7456e97a4f4/exampleSite/config.toml#L553

**Comment by HEIGE-PCloud** [comment]
There have been many reports of this problem, and I am curious how people use and configure the theme for the first time. If you follow the documentation on the website https://hugodoit.pages.dev/theme-documentation-basics/ (which I "assume" most people do, and I consider it as the correct practice), you should not encounter this issue (since bundle as an experimental option is not described there). But if you copy the config.toml from exampleSite directly (which is not an ideal approach), you will meet with this problem.

How can I make this better? Maybe add an [warnf](https://gohugo.io/functions/errorf/) when bundle is set to true? (Of course, the best way is to finish the refactor soon so this problem does not happen anymore...)

**Comment by eyllanesc** [comment]
@HEIGE-PCloud People never follow the "right path" so the developer should take the time to explain the new feature. 

In my personal case when I try a new technology I always copy the examples and see if something breaks, after playing for a while I just read the tutorials, I think that's the funniest way to learn: first break it and then understand why it breaks . 

I propose:

- Place a warning in the log indicating that `bundle=true` is experimental and should not be used.
- Place a warning explaining the same thing on the website(in https://hugodoit.pages.dev/theme-documentation-basics/).
- It would also be good to explain what `bundle=true` does, and how to try to configure it even though it is experimental, obviously the user must assume his own risks. I like to use the latest features.

In general, this logic should have any characteristic so that the transition is not abrupt but rather smooth.

**Comment by eyllanesc** [comment]
@HEIGE-PCloud Note: if this is a "bug" already reported in another issue then close it as a duplicate.

**Comment by Huoke** [comment]
I think the main reason for this problem is that the error logs prompt is not accurate enough
