### ISSUE TITLE
[Enhancement/discussion] More distinguishable font size between different levels of header

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#492]
### Describe the feature you want 描述你的功能需求

In posts with multiple levels, it's hard to know if a given header is at the same level or not.

There is some pixel difference already, while, I wonder, if it's possible to make the headline much larger or in different styles?

This was triggered by one of my readers from https://www.siwei.io/resolve-wordle/, where she was confused about the header levels(before I told her there is a TOC).

Not sure about the solution but just to bring this topic for discussion.

What do you think, please?

**Comment by HEIGE-PCloud** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/52968553/156551023-859c8fc6-bd05-4836-934e-e26581da86db.png">

This is the current font sizes for different heading in DoIt. The difference between different heading is only 2px, so it is a bit insignificant.

If we increase the size difference to 4px, and set the base size for h6 to be 20px (4px larger than the paragraph), it looks something like this.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/52968553/156553519-3b0e48e5-fc5b-4712-b3dc-9cc1d4aee487.png">

I personally find 32px bold for h2 heading is a bit too thick. And the margin around the heading seems to need more adjustment as well...

What do you think? Also check out the pr #498 for preview.

https://do-it-git-typography-heading-pcloud.vercel.app/markdown-tests/#h2-225rem-36px

**Comment by HEIGE-PCloud** [comment]
As a reference, the browser default stylesheet set h4 as the base point (1em) and scale up in a non-linear way.

| tag | font-size |    px   |
|:---:|-----------|:-------:|
|  h1 |    2em    |   32px  |
|  h2 |   1.5em   |   24px  |
|  h3 |   1.17em  | 18.72px |
|  h4 |    1em    |   16px  |
|  h5 |   .83em   | 13.28px |
|  h6 |   .67em   | 10.72px |

**Comment by wey-gu** [comment]
Thanks so much, @HEIGE-PCloud for your kind help in putting times on this thread(my issue is not even reasonable though)!

- I just noticed that the feeling of differences in my mind is actually exponential rather than linear as you have shown as references from the default browser behavior.
- I agree that 32px is too thick already.
- I guess the reason why the original design in *it so(that there are almost no differences from h2 to h4) was willing to make the paragraph font larger.

Thus, with given upper bound(32), lower bound(16), and layer(6), it's not possible to have proper exponential differences in all layers.

Then, the solutions could be:
a. user: Use non-continuous headers like h1->h2->h6
b. user: Only use H1 and H2 when possible(if we insist on using continuous headers)
c. design-change: Introduce elements rather than **only font-size** to demonstrate headers, i.e. use different styles/colors of that `|` at the beginning of the header for odd/even header layers or?

For a. or b. I will prefer b. (Now I started header from H2, where the curve was quite flat from H2 to H4, which could be avoided in the future.)

For c. I am not sure if it makes any sense to you.

Thanks again!!!

**Comment by HEIGE-PCloud** [comment]
a. You definitely should not use non-continuous headers. The table of content completely depends on the headers to determine its nesting, and non-continuous headers will generate a very ugly result.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/52968553/156597146-0ba73b58-d433-412b-a23c-f60c8ca4462e.png">

b. In fact, it is recommended to always start with a h2 header (`## header` in Markdown). Multiple h1 headers on one page is not considered the [best practice](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#multiple_h1_elements_on_one_page). The only h1 header on the page is the title  of the post at the very top, so semantically, it makes sense to start a chapter in a h2 tag.

A side note here. On siwei.io, it seems that you have set the `startLevel` to `1` instead of `2`, resulting in an always indented toc.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/52968553/156601406-05415f08-f1ab-4fcd-a940-7db6de648c69.png">

If you have decided to always start with a h2 tag, change `markup.tableOfContents` in config.toml to this

```toml
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
```

to make it looks better.

In my opinion, the easiest thing the user can do to make headings clearer is to manually add serial numbers in the front of each header.
For example, on the [example site](https://hugodoit.pages.dev/theme-documentation-basics/#21-create-your-project), it places "1", "2.1", "2.2" in the front of each header, which makes it easier to read. I am not sure whether it is easy to implement a function which automatically generates the serial number, but it can be a solution.

I agree that changing other elements (may be font-weight and font-style) can make it better, but it needs to be very careful or the page can easily be messy. I probably need to do more research on typography to see how I should design it.

**Comment by wey-gu** [comment]
Thanks!
Typing from mobile GitHub now.
- I will look into the start level when I could!
- I should go with the 1.1.foo style heading ;)

Thanks again, have a good night!

Regards, Wey

**Comment by HEIGE-PCloud** [comment]
@wey-gu It turns out it is quite easy to enable heading numbering by pure CSS.

https://do-it-46gvlglca-pcloud.vercel.app/markdown-tests/

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/52968553/156861171-3bf7c79d-c1ca-4641-9d6b-1608bdc95252.png">

Is this something useful?

**Comment by wey-gu** [comment]
> @wey-gu It turns out it is quite easy to enable heading numbering by pure CSS.
> 
> 
> 
> https://do-it-46gvlglca-pcloud.vercel.app/markdown-tests/
> 
> 
> 
> <img width="1080" alt="image" src="https://user-images.githubusercontent.com/52968553/156861171-3bf7c79d-c1ca-4641-9d6b-1608bdc95252.png">
> 
> 
> 
> Is this something useful?

This.... is beyond useful, instead, it's terribly awesome to me 😭.

Cheers// Wey

**Comment by wey-gu** [comment]
I'm really eager to see this could become a feature!🤩

**Comment by wey-gu** [comment]
Closing it as #508 addressed it in an elegant way.
Thanks again @HEIGE-PCloud 😭.
