### ISSUE TITLE
[question] on Syntax Highlighting of Cypher

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#500]
### Describe the bug 描述你遇到的错误

If I understand it correctly, from [here](https://gohugo.io/content-management/syntax-highlighting), hugo is leveraging chroma to enable syntax highlighting.

From here:

https://github.com/alecthomas/chroma/blob/9de08fc6c8a378c8d2e58930c09d2ab9b8ec26f0/pygments-lexers.txt#L117

We could see cypher is supported, while, in doit, it was not properly highlighted.

From [this post](https://www.siwei.io/resolve-wordle/) we could tell the cypher code blocks in post area and comment area are highlighted differently.

ref: [pygments.lexers.graph.CypherLexer](https://pygments.org/docs/lexers/#lexers-for-graph-query-languages)

### Expected behavior 期待的行为

As it was rendered in the comment system [Waline](https://github.com/walinejs/waline)

### Screenshots 屏幕截图

<img width="1156" alt="Screen Shot 2022-03-03 at 10 59 37 PM" src="https://user-images.githubusercontent.com/1651790/156590725-63a82a58-5d2f-4597-b8d9-61d92c9575f7.png">

### Build Environment 构建环境

```bash
hugo version
hugo v0.91.2+extended darwin/arm64
```

### Preview Environment 预览环境

```bash
hugo version
hugo v0.91.2+extended darwin/arm64
```

### Additional Information 补充信息

na

**Comment by HEIGE-PCloud** [comment]
Hugo does not seem to recognize the language and uses `language-fallback` for the code block. I am afraid there is not much the theme can do for it.

I suspect it is caused by a mismatch in the language name. In the [chroma playground](https://swapoff.org/chroma/playground/), I didn't see a language called "cypher", maybe use `GraphQL` for the language code can get the highlighting to work.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/52968553/156595187-a6bb239e-e2fd-42d3-bb4b-af486fc09963.png">

**Comment by wey-gu** [comment]
Thanks @HEIGE-PCloud !

I am mitigating with `GraphQL` now, it's actually quite interesting that GraphQL isn't about Graph in most cases.(one exception is that dgraph had been trying to make their graph query language similar to GraphQL.)
