### ISSUE TITLE
Code content doesn't render newlines

### ISSUE THREAD

**Issue by Thanatermesis** [HEIGE-PCloud/DoIt#613]
I was reading the documentation and seems like there's a small issue in the **11.2 code content** of https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#simple-content , where seems like the newlines are not rendered

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/blob/5a23fa10c1cfd227e7c3d664f1a3f26313130fc4/layouts/shortcodes/typeit.html#L8-L15

DoIt uses some dirty hack to process the code block for TypeIt, the code block HTML generated by Hugo is changed from 0.93.0 which causes this problem.

The issue is also tracked here #515
