### ISSUE TITLE
[BUG] Admonition and image shortcode problem

### ISSUE THREAD

**Issue by foxdie987** [HEIGE-PCloud/DoIt#885]
### Describe the bug 描述你遇到的错误

I encountered Admonition and image shortcode problem. They have been working together well before, but at current 0.3.0 version, they stop working.

### Expected behavior 期待的行为

The issue is that image shortcode produces a text code like screenshot below instead of rendering the picture properly, while is nested inside Admonition shortcode.

```
{{< admonition type=abstract title="..." open=false >}}
{{< image src="/images/misc/Watergate_1.jpg" caption="Anni 10 (2)" linked=false >}}
{{< /admonition >}}
```

### Screenshots 屏幕截图

![Capture](https://user-images.githubusercontent.com/64511386/224902741-806739f5-7864-45a0-afe0-ec4c0ef03971.JPG)

### Build Environment 构建环境
Theme version: 0.3.0
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z
Deployed from Cloudflare Pages.

### Additional Information 补充信息

Meanwhile Basic Images markdown syntax such as `![Alt text](https://octodex.github.com/images/stormtroopocat.jpg "The Stormtroopocat")` has no problem when I use together with Admonition shortcode,

**Comment by HEIGE-PCloud** [comment]
This problem is rather more difficult than I think. You see, the logic of the admonition shortcode is to first render its inner content from Markdown to HTML, then wrap them within a styled `div`. The problem is when a shortcode is nested, it is rendered before its parent. So in this case

```
{{ admonition shortcode}}
  {{ image shortcode }}
{{ /admonition shortcode}}
```

The image shortcode gets rendered first

```
{{ admonition shortcode}}
  <img src="...">
{{ /admonition shortcode}}
```
 
Then the admonition shortcode renders, which attempts to parse the HTML code as Markdown, and break the HTML code.

```
<div>
  <broken-img>
</div>
```

The native Markdown syntax survived because, well, it is the native syntax, so the render hook is called while rendering the admonition shortcode.

I am not very sure how to get around this issue, any suggestions are appreciated.

**Comment by HEIGE-PCloud** [comment]
Yep, known issue. No nesting shortcode. https://github.com/gohugoio/hugo/issues/7848

**Comment by hugosxm** [comment]
Hi @HEIGE-PCloud , Maybe I have the same kind of problem but doing this : 

```
{{< style "text-align:center; img{border-radius: 50%;}" >}}
{{< image src="/images/avatar.png" alt="profile-picture" width="25%" height="25%">}}
{{< /style >}}
```

The image is not displayed, but i just switched from LoveIt theme, which works in this case, so maybe there is something to investigate ?
