### ISSUE TITLE
How to upgrade deps easier?

### ISSUE THREAD

**Issue by eallion** [HEIGE-PCloud/DoIt#953]
### Describe the bug 描述你遇到的错误

For example, the latest version of algoliasearch is 4.17.0, but the version in the theme is still 4.11.0.
Is there an easier way to upgrade the version? The best way is automatic.

**Comment by HEIGE-PCloud** [comment]
Yes, upgrading dependencies is a pain. Currently all dependencies are directly committed to the [repository](https://github.com/HEIGE-PCloud/DoIt/tree/main/assets/lib), and I wrote a custom [GitHub Action](https://github.com/Hugo-DoIt/update-dependencies) to check for updates every day and create [pull requests](https://github.com/HEIGE-PCloud/DoIt/pull/937). If you find anything missing, you can create a PR to amend to this custom [`dependencies.json`](https://github.com/HEIGE-PCloud/DoIt/blob/main/dependencies.json) so it can be updated automatically. Ideally, users just need to update the theme from time to time and all dependencies will be up to date.

I had attempted to use `package.json` and a package manager like `npm` to manage dependencies before. However, this adds a lot of extra complexities for both the development process and the end users since `npm` does not work well with Hugo.

- [`js.build`](https://gohugo.io/hugo-pipes/js/) extra build step for every npm dependencies.
- Code splitting is more difficult, may result in larger bundle size.
- Bad CDN support.
- Extra dependencies (`node`, `npm`) are required for the end user.
- Extra build steps [`hugo mod npm pack`](https://gohugo.io/commands/hugo_mod_npm_pack/) and `npm install` for the end user.

I discussed some other issues that I run into in this [discussion thread](https://github.com/HEIGE-PCloud/DoIt/discussions/371).

**Comment by eallion** [comment]
Can i use this [GitHub Action](https://github.com/Hugo-DoIt/update-dependencies) in my Hugo project?

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> Can i use this [GitHub Action](https://github.com/Hugo-DoIt/update-dependencies) in my Hugo project?

gh-action can upgrade deps in your repo, If you want to upgrade your local dependencies, you still need to `git pull`

if you are running your hugo site on a server, try `crontab` with `npm`?
