### ISSUE TITLE
[BUG] After tailwind's `main.css` is added, under `hugo server` command, Markdown list is no longer showing numbering

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#957]
### Describe the bug 描述你遇到的错误

https://github.com/HEIGE-PCloud/DoIt/pull/956/files#diff-b15932692c619f9a334ecb156ac167557c3af214a8a3df8990c09232ac8a5baaR336 (please click load diff to see the particular line in `main.css`) is causing a bug where a markdown like

``` markdown
1. aaa
2. bbb
3. ccc
```

Is now rendering as:

```
	aaa
	bbb
	ccc
```

When running `hugo server` command

### Expected behavior 期待的行为

It should be rendered as 

``` markdown
1. aaa
2. bbb
3. ccc
```

### Screenshots 屏幕截图

This is the current behaviour:

![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/1c7e5414-7e45-472a-8fc6-c45b1f830611)

This is the expected behaviour which used to be working:

![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/afbae5bf-57c2-4867-a1d5-c523eaf960a0)

### Build Environment 构建环境

- OS: Debian in Docker Container
- Theme version:  3f235ab
- Hugo version: v0.111.3

### Preview Environment 预览环境

- OS: Win 10 Pro 22h2
- Browser: Brave (a Chromium browser)

### Additional Information 补充信息

This is not reproducible using `hugo build` command. This issue only appears when using `hugo server` command to preview the site

Removing this particular line https://github.com/HEIGE-PCloud/DoIt/pull/956/files#diff-b15932692c619f9a334ecb156ac167557c3af214a8a3df8990c09232ac8a5baaR336 can solve the issue, but I believe there should be a better fix

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
The tailwind css style overwrites the original scss style. In fact, the tailwind css file `tailwind.css` has just been created and just contain some basic style, the content inside `main.css` is basically the template made by official, it will not and should not have an impact on the style of the theme.

**Comment by HEIGE-PCloud** [comment]
I plan to slowly migrate the original SCSS to Tailwind CSS after experiencing a lot of issues with coupled CSS styles. Sometimes I edit a property to fix one issue, but this edit will break other parts of the theme. Tailwind CSS makes styles atomic, so the styles are decoupled at least at the selector level. I do think it also improves DX significantly when I implement the new [tab shortcode](https://github.com/HEIGE-PCloud/DoIt/pull/960).

The migration process is quite tricky, since if there is some unintended conflicts in style, we will not be able to know it immediately. I have added a custom prefix `tw-` to all Tailwind CSS styles so that prevents most class name clashes. Tailwind CSS also comes with a "base style", which is just its own `normalize.css` that unsets some browser default styles to make custom styling easier. However, its base style is not the same as the `normalize.css` DoIt is currently using, and DoIt does rely on some browser default styles (like for headings, and in this case, list items). I don't want to opt out for the base layer, since it is quite useful for adding new styles, however I do expect to it to break a small number of existing styles, which can be fixed quite easily by extending the layer and add default styles.
